### ISSUE TITLE
Basket icon disappeared?

### ISSUE THREAD

**Issue by cdeeter09** [donhinkelman/moodle-block_sharing_cart#141]
In one of our Moodle instances, the sharing cart plug-in is turned on, and you can add the block to the side panel, but there is no chart or basket popping up in activity like it used to. In some of the course formats the Activity Clipboard has been activated, but it is still not activating the sharing cart. There is also no drag and drop functionality to it right now. You can click on the activity you want to drag, and the sharing cart will blur and say "drop here" but it pulls over all the content from the site/topic and will not let you drop anything into the cart block.

**Comment by donhinkelman** [comment]
Thank you for your issue report. I believe this is fixed in the latest release of the Sharing Cart. Please check that you have installed it. This most recent release restores the basket icon as default. Previously, the basket icon was removed as default in order to promote drag-and-drop sharing cart operation. However, that was confusing to many users, so the basket icon was restored.

**Comment by cdeeter09** [comment]
Our instance had updated within the timeframe of the latest update being released. But i will check to ensure that we are running the correct version of the plug-in to make sure everything is up to date, thank you.

**Comment by frederikmillingpytlick** [comment]
This seems resolved, closing issue
