### ISSUE TITLE
tag the releases

### ISSUE THREAD

**Issue by taraghi** [donhinkelman/moodle-block_sharing_cart#143]
Would you mind tagging the releases?

This would help us easily integrate the releases into our Moodle environment via our CI process.

Thank you!

**Comment by donhinkelman** [comment]
Hi Taraghi, yes I can tag the releases, but you will have to instruct me how. I am not familiar with github, but I am happy to learn and be a better maintainer.

**Comment by AraPraxis** [comment]
Hello @donhinkelman,
as the programming team, we can easily add this when updating the plugin.

We don't use tags normally so we'll try to remind eachother as much as possible when updating the plugin - I'll hereto update the README.md on our next fix, telling people to tag with the newest release number. So that everyone knows that it's a necessity.

Kind regards,
Anders Rasmussen

Praxis Team
