### ISSUE TITLE
Backup of only Quiz contains files

### ISSUE THREAD

**Issue by lassnj** [donhinkelman/moodle-block_sharing_cart#174]
When I look at the Backup of a Quiz Activity, also Files are part of the backup. They take up a lot of space and thus putting the quiz into the sharing cart takes a lot of time. Is there a way to exclude these files?
Thanks!

Content of the Quiz-Backup
![grafik](https://github.com/donhinkelman/moodle-block_sharing_cart/assets/22933650/2a3ce03e-5248-4e52-a9de-6a30a670129b)

**Comment by AraPraxis** [comment]
Hello @lassnj

We use Moodle's backup/restore functionality. The files are needed to make sure the backup/restore functionality works as intended.

If you have any further problems or questions, then feel free to open the issue again or create a new one.

Kind regards,
Anders Rasmussen

Moxis Team

**Comment by lassnj** [comment]
Sharing Cart seems to use the default settings for the Backup. We include everything from the course in the default settings so that the teachers don't need to check all the boxes. But for a quiz Backup the Blocks and Files of the course are not needed. The sharing cart backup has almost the same size as the backup of the quiz with the default settings whereas the backup where I only included activities and the question bank has just a fraction of the size. Could you make the backup process more efficient and only include what is really needed? 
Thanks a lot!

![grafik](https://github.com/user-attachments/assets/cb7bbee8-2bca-49a9-a83e-9fac7dad88b0)

**Comment by donhinkelman** [comment]
Dear Lassnj, you have put your finger on the oldest open bug in Moodle LMS history, first filed in 2007. The core backup functions (which the Sharing Cart uses) will backup everything, rather than just the necessary items. Backup functions are incapable of "minimization" which some people call a feature request but every user like you and me, experiences as a serious bug. This bug may be fixed with the Question Bank consortium changes in the Quiz and Question Bank versions 4.0-4.5, but it seems this bug fix is being postponed in every release.

Please go to the Moodle LMS bug tracker and add your vote and comment to these two issues:
- MDL-12403
- MDL-41924

**Comment by lassnj** [comment]
Hi Don,
thanks for pointing out the Moodle LMS bugs. Already voted and subscribed ;)
However, the bugs only concern the question.xml. My problem are the files that are also included when everything of the backup process is checked, when I only select to backup activities and question bank the backup file of the same quiz reduces to 1.9 MB instead of 202 MB. 
Just excluding the files is actually sufficient to reduce the size of the backup:
![grafik](https://github.com/user-attachments/assets/633e9748-d9dc-4436-9267-1ed28de8678c)
