### ISSUE TITLE
Some users can copy Glossaries with user data, others can not.

### ISSUE THREAD

**Issue by losborne23** [donhinkelman/moodle-block_sharing_cart#33]
Versions
Moodle: 3.7
Sharing Cart: 3.6, release 1 (2019012000)

Sharing cart has been an awesome tool. Some of our teachers like to make a glossary and then copy it other similar courses they teach. When I use sharing cart to move the glossary, it asks if I want to include user data. However, if the teacher of the course tries to use the sharing cart, it does not ask about user data and only moves the blank glossary, without user data. Any ideas why that might be?

**Comment by donhinkelman** [comment]
I believe you have reported an issue we need to fix. Thank you very much. I assume that your role is an "admin" and that your teachers have a "manager" role. It means the Sharing Cart's intention to optionally move user data only works for admins. This means the permissions need to be changed.

**Comment by TubsDK** [comment]
To be able to copy glossary the teacher role needs the capability moodle/backup:userinfo,moodle/backup:anonymis  and moodle/restore:userinfo since glossary entries are considered userdata.

**Comment by donhinkelman** [comment]
Thanks, TubsDK, for closing the issue. Help me understand what the problem was and how it was fixed. Did you change any code? Or was Losbourne using the SC improperly or with wrong settings?  If I understand this, then I can change the documentation to explain to other users. Actually, I had a similar problem once like Losbourne did.
