### ISSUE TITLE
Problem with adding H5P-Content to Sharing-Cart

### ISSUE THREAD

**Issue by BiLachner** [donhinkelman/moodle-block_sharing_cart#43]
Hi,
my and my colleagues tested the sharing-cart on the local moodle-Installation that is used for several schools.
On our testing-installation it works fine, but now H5P causes a long during lag and you need to change the browser to continue using moodle.
-> moodle-Version 3.7
-> H5P-Version not the latest, but maybe a version before.
Other activities work fine.

Does anyone has any idea?

Birgit

**Comment by Mikkeljeppesen1** [comment]
@BiLachner 

I just tested this on a brand new Moodle installation (3.7) and I experience that it took a bit to copy and restore but I don't need to switch browser. 

And about lag? Yes it takes a bit to copy, but I don't  know what you mean about lag

**Comment by Urpokarhu1** [comment]
it takes about 20 minutes to copy one h5p to sharing cart but you can reduce this time by changing h5p settings that it doesn't include all libraries in every backup

**Comment by donhinkelman** [comment]
I hope someone can test moving H5P content with Sharing Cart 3.8 on a Moodle 3.9 site. I am wondering if the problem is: a) H5P or b) question bank in general. For the past 13 years, slow copying of quizzes is a constant complaint because the question bank copies a whole site's questions, not minimizing the questions copied to only needed ones.

**Comment by jprovasnik** [comment]
I experience the same issue on Moodle 3.7 (I'm hosted so i'm not sure how to debug to see what's causing the issue). But when I add and H5P item into my sharing cart -- the page spins for about 10 minutes. 
Urpokarhu1 -- how do you "change h5p settings so that it doesn't include all libraries in every backup"
Is that done through the Moodle settings interface, or is that done by modifying code?

**Comment by Urpokarhu1** [comment]
Hello,

The setting is $CFG->mod_hvp_backup_libraries=0;

**Comment by Mikkeljeppesen1** [comment]
Hey guys

I know that hvp is an issue when it comes to using sharing cart. I know they trying to make hvp a moodle core thing, and they try to integrate it in moodle 3.9. 

Please use the setting Urpokarhu1 provided above - it helps!!!

To donhinkelman, I can tell you that question bank is a problem too if you don't create the quiz in the right way

**Comment by donhinkelman** [comment]
Which file and which line should the setting:  **$CFG->mod_hvp_backup_libraries=0**     be inserted?  
Shouldn't this be part of core? 
Also, "...question bank is a problem too if you don't create the quiz in the right way..."  Haha. Don't get me started. Yeah if you don't try to **share** questions in the question bank. If you keep the questions to yourself at the narrowest context, no problem.

**Comment by Mikkeljeppesen1** [comment]
it should be in your config file for your site

**Comment by donhinkelman** [comment]
Thanks!  And sorry for my laughter. If you have some specific suggestions on how to create a quiz the right way, I am interested.
