### ISSUE TITLE
Improvement: capability "copy resources"

### ISSUE THREAD

**Issue by jharej** [donhinkelman/moodle-block_sharing_cart#45]
Hi,

we're planning to run a project where we would build quite a big collection of courses open to all teachers. We see these courses as a library of resources and activities that teachers can just take and use. We would like to offer the teachers the option to copy any resource, but we can not give them an editing role. We are thinking of using this plugin to support this option.

Since they can not have editing roles, we see that this plugin should be upgraded in a way that it would be possible for the specific role that would have a certain capability (e.g. new capability copy resources, but not editing role) to copy any resource from the course.  

Would this kind of upgrade be in the interest of authors? If we get this project, we would be prepared to finance this upgrade. I hope I described the issue clear enough. 

Thanks
Janko

**Comment by donhinkelman** [comment]
I am always in favor of any plans to improve sharing of course materials and teacher to teacher collaboration. What you are proposing sounds similar to what MoodleNet is planning, right? Let's see what they are releasing in the MoodleMoot Global in July. Also, we have to urge Moodle HQ to fix the big bugs in the question bank which are preventing sharing like you propose--see MDL-12403: original “Backup/Import of single quiz includes all questions in database”  Bug—critical and MDL-41924: Minimize questions in Question Bank

**Comment by jharej** [comment]
As I see it, MoodleNet will provide the possibility to share an activity/resource on their network. If we want to enable sharing among teachers, I have to install MoodleNet - local instance and motivate the teachers to use the new platform ... Regarding the bugs ... I see that we should only warn the teachers that copying the quiz does not always work correctly. 
Does your plugin support copying of h5p activities?

**Comment by PraxisService** [comment]
Hello Janko,

This is not a feature we can implement, since we are using moodle core capabilities for several tasks. We are using moodle core functions to restore activities and resources. At the same time, the sharing cart block is only shown, when editing is on, this is another moodle capability that needs to be bypassed.

The best solution i can think of, is that you make a new user role on your site, grant permissions so the role can edit courses and restore activities/resources. And then add the role to the teachers.


Kind regards,
Daniel
