### ISSUE TITLE
XMLDB errors

### ISSUE THREAD

**Issue by haietza** [donhinkelman/moodle-block_sharing_cart#6]
Just updated to version 2019012000 and received these DB errors:

XMLDB has detected one CHAR NOT NULL column (name) with '' (empty string) as DEFAULT value. This type of columns must have one meaningful DEFAULT declared or none (NULL). XMLDB have fixed it automatically changing it to none (NULL). The process will continue ok and proper defaults will be created accordingly with each DB requirements. Please fix it in source (XML and/or upgrade script) to avoid this message to be displayed.
line 1733 of /lib/datalib.php: call to debugging()
line 352 of /lib/xmldb/xmldb_object.php: call to xmldb_debug()
line 255 of /lib/xmldb/xmldb_field.php: call to xmldb_object->debug()
line 131 of /lib/xmldb/xmldb_field.php: call to xmldb_field->setDefault()
line 103 of /lib/xmldb/xmldb_field.php: call to xmldb_field->set_attributes()
line 781 of /lib/xmldb/xmldb_table.php: call to xmldb_field->__construct()
line 121 of /blocks/sharing_cart/db/upgrade.php: call to xmldb_table->add_field()
line 1003 of /lib/upgradelib.php: call to xmldb_block_sharing_cart_upgrade()
line 520 of /lib/upgradelib.php: call to upgrade_plugins_blocks()
line 1852 of /lib/upgradelib.php: call to upgrade_plugins()
line 694 of /admin/index.php: call to upgrade_noncore()
XMLDB has detected one TEXT/BINARY column (summary) with some DEFAULT defined. This type of columns cannot have any default value. Please fix it in source (XML and/or upgrade script) to avoid this message to be displayed.
line 1733 of /lib/datalib.php: call to debugging()
line 352 of /lib/xmldb/xmldb_object.php: call to xmldb_debug()
line 261 of /lib/xmldb/xmldb_field.php: call to xmldb_object->debug()
line 131 of /lib/xmldb/xmldb_field.php: call to xmldb_field->setDefault()
line 103 of /lib/xmldb/xmldb_field.php: call to xmldb_field->set_attributes()
line 781 of /lib/xmldb/xmldb_table.php: call to xmldb_field->__construct()
line 122 of /blocks/sharing_cart/db/upgrade.php: call to xmldb_table->add_field()
line 1003 of /lib/upgradelib.php: call to xmldb_block_sharing_cart_upgrade()
line 520 of /lib/upgradelib.php: call to upgrade_plugins_blocks()
line 1852 of /lib/upgradelib.php: call to upgrade_plugins()
line 694 of /admin/index.php: call to upgrade_noncore()

**Comment by abias** [comment]
The root of these warnings are located in https://github.com/donhinkelman/moodle-block_sharing_cart/blob/master/db/upgrade.php#L121-L122 in https://github.com/donhinkelman/moodle-block_sharing_cart/blob/master/db/install.xml#L43-L44. The definitions of the table in install.xml don't match the instructions for upgrading the plugin in upgrade.php.

From my point of view, this has to be done:
* Decide which of both files produces the correct DB table structure.
* Synchronize both files so that they produce the same DB table structure
* Analyse the status of Moodle instances which have upgrades with the given upgrade.php step and fix them if necessary in a new upgrade.php step.

**Comment by johnnypraxis** [comment]
Fixed :-)
